---
- name: Install my dotfiles and programs on an empty debian-based server
  hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
  tasks:
    - name: Install CLI tools, configure shell and tmux
      ansible.builtin.include_tasks: tasks/term.yml
    - name: Install and configure sway and waybar
      ansible.builtin.include_tasks: tasks/sway.yml
    - name: Install common GUI apps
      ansible.builtin.include_tasks: tasks/apps.yml
    - name: Install and configure catppuccin theme
      ansible.builtin.include_tasks: tasks/catppuccin.yml
    - name: Install and configure Neovim
      ansible.builtin.include_tasks: tasks/neovim.yml
    - name: Download wallpapers
      ansible.builtin.include_tasks: tasks/wallpapers.yml
