---
- name: Install GUI tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - xournal
    - gimp
    - rhythmbox
    - shotwell
    - openscad
    - inkscape
    - pavucontrol
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin

- name: Remove GUI tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - krita
    - foot
