---
- name: Install GUI tools
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - xournal
    - gimp
    - rhythmbox
    - shotwell
    - openscad
    - inkscape
    - blender
    - krita
