---
- name: Install GUI tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xournal
    - gimp
    - rhythmbox
    - shotwell
    - openscad
    - inkscape
    # - blender
    - krita
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
