---
# here are all the customization for catppuccin themes
# we checkout the different themes from github organizations:

# things used by the themes
- name: Install fonts and themes deps
  become: true
  ansible.builtin.apt:
    name:
      - fonts-font-awesome
      - fonts-hack
      - fonts-noto-color-emoji
      - gnome-themes-extra
      - gnome-settings-daemon
      - libgtk-4-1
    install_recommends: false
    state: present

#
# GRUB
#
- name: Check if grub is installed
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: grub_install_check


- name: Clone catppuccin/grub
  ansible.builtin.git:
    repo: https://github.com/catppuccin/grub.git
    version: 88f6124
    dest: ./temp/catppuccin/grub
    accept_hostkey: true
    clone: true
    update: true
    depth: 1
  when: not grub_install_check.stat.exists

- name: Copy theme files for grub
  become: true
  ansible.builtin.copy:
    src: ./temp/catppuccin/grub/src/catppuccin-mocha-grub-theme
    dest: /usr/share/grub/themes
    owner: root
    group: root
    mode: "755"
  when: not grub_install_check.stat.exists

- name: Check if theme is configured in the boot command
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: ^GRUB_THEME=".*
    state: absent
  check_mode: true
  register: grub_theme_check
  changed_when: false
  when: not grub_install_check.stat.exists

- name: Enable the theme in grub default configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha-grub-theme/theme.txt"
    # create: true
  when: not grub_install_check.stat.exists and grub_theme_check.found is defined and grub_theme_check.found == 0

- name: Update grub if theme was added
  become: true
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  when: not grub_install_check.stat.exists and grub_theme_check.found is defined and grub_theme_check.found == 0
  changed_when: true

#
# TTY : https://github.com/catppuccin/tty
#
- name: Clone catppuccin/tty
  ansible.builtin.git:
    repo: https://github.com/catppuccin/tty.git
    version: d18074f
    dest: ./temp/catppuccin/tty
    clone: true
    update: true
    depth: 1

- name: Check if tty theme is configured in the boot command
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=".*vt.*"$
    state: absent
  check_mode: true
  register: grub_tty_check
  changed_when: false

- name: Generate mocha theme
  ansible.builtin.command:
    chdir: ./temp/catppuccin/tty
    cmd: ./generate.sh mocha
  register: tty_theme
  when: grub_tty_check.found is defined and grub_tty_check.found == 0

# FIXME; this does not work when config exists
- name: Configure tty theme in GRUB_CMDLINE_LINUX options
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    backrefs: true
    regexp: "^(GRUB_CMDLINE_LINUX=\")(.*\")$"
    line: '\1{{ tty_theme.stdout }}\2'
  when: grub_tty_check.found is defined and grub_tty_check.found == 0 and grub_install_check.stat.exists

- name: Update grub if tty config was added
  become: true
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_tty_check.found is defined and grub_tty_check.found == 0 and grub_install_check.stat.exists

# Plymouth
- name: Activate splash screen in GRUB_CMDLINE_LINUX_DEFAULT options
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    backrefs: true
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\")(.*\")$"
    line: '\1quiet splash"'

- name: Ensure plymouth theme folder exists
  become: true
  ansible.builtin.file:
    path: /usr/share/plymouth/themes/blgt
    recurse: true
    state: directory

- name: Copy plymouth theme files
  become: true
  ansible.builtin.copy:
    src: "./config/plymouth/themes/blgt/{{ item }}"
    dest: "/usr/share/plymouth/themes/blgt/{{ item }}"
  loop:
    - blgt.plymouth
    - blgt.script
    - logo.png

- name: Update alternatives for plymouth theme
  become: true
  ansible.builtin.shell: >
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/blgt/blgt.plymouth 100
    update-alternatives --set default.plymouth /usr/share/plymouth/themes/blgt/blgt.plymouth
    update-initramfs -u
#
# Waybar https://github.com/catppuccin/waybar
#
- name: Clone catppuccin/waybar
  ansible.builtin.git:
    repo: https://github.com/catppuccin/waybar.git
    version: ee8ed32
    dest: ./temp/catppuccin/waybar
    clone: true
    update: true
    depth: 1

- name: Ensure waybar config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/waybar
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy mocha theme files for waybar
  ansible.builtin.copy:
    src: ./temp/catppuccin/waybar/themes/mocha.css
    dest: /home/{{ user }}/.config/waybar
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

#
# tmux: https://github.com/catppuccin/tmux
# 
- name: Ensure tmux plugins directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/tmux/plugins
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Ensure cattpuccin directory exists
  ansible.builtin.stat:
    path: /home/{{ user }}/.config/tmux/plugins/catppuccin
  register: catppuccin_tmux_plugin

- name: Clone catppuccin/tmux
  when: catppuccin_tmux_plugin is undefined
  ansible.builtin.git:
    repo: https://github.com/catppuccin/tmux.git
    version: v2.1.2
    dest: /home/{{ user }}/.config/tmux/plugins/catppuccin
    clone: true
    update: true
    depth: 1

#
# btop https://github.com/catppuccin/btop
#
- name: Clone catppuccin/btop
  ansible.builtin.git:
    repo: https://github.com/catppuccin/btop.git
    version: 21b8d59
    dest: ./temp/catppuccin/btop
    clone: true
    update: true
    depth: 1

- name: Ensure btop config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/btop/themes
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy mocha theme file for btop
  ansible.builtin.copy:
    src: ./temp/catppuccin/btop/themes/catppuccin_mocha.theme
    dest: /home/{{ user }}/.config/btop/themes/catppuccin.theme
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

#
# GTK https://github.com/catppuccin/gtk
#
- name: Set gtk theme variable
  ansible.builtin.set_fact:
    gtk_theme: catppuccin-mocha-teal-standard+default

- name : Ensure user themes directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.themes
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Download and install catppuccin/gtk to themes
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/gtk/releases/download/v1.0.3/{{ gtk_theme }}.zip
    dest: /home/{{ user }}/.themes/
    creates: /home/{{ user }}/.themes/{{ gtk_theme }}
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name : Ensure gtk-4.0 and gtk-3.0 config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/{{ item }}
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - gtk-4.0
    - gtk-3.0

- name: Copy settings.ini for gtk
  ansible.builtin.copy:
    src: ./config/gtk/settings.ini
    dest: /home/{{ user }}/.config/{{ item }}/settings.ini
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - gtk-3.0
    - gtk-4.0

- name: Create symbolic links for gtk-4.0
  ansible.builtin.file:
    src: /home/{{ user }}/.themes/{{ gtk_theme }}/gtk-4.0/{{ item }}
    dest: /home/{{ user }}/.config/gtk-4.0/{{ item }}
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - assets
    - gtk.css
    - gtk-dark.css

- name: Enable theme in profile and rc files
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/{{ item }}
    line: export GTK_THEME="{{ gtk_theme }}"
    create: true
  loop:
    - .profile
    - .zshrc
    - .bashrc

- name: Enable theme in settings
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.config/gtk-3.0/settings.ini
    line: gtk-theme-name={{ gtk_theme }}

# Icons and cursors theme : Qogir ( https://github.com/vinceliuice/Qogir-icon-theme/ )

- name: Clone Qogir icon theme
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/Qogir-icon-theme.git
    version: 0b90905
    dest: ./temp/qogir-icon-theme
    clone: true
    update: true
    depth: 1

- name: Check if qogir icon theme is installed
  ansible.builtin.stat:
    path: /usr/share/icons/Qogir
  register: qogir_icon_check

- name: Install icon theme
  ansible.builtin.command:
    chdir: ./temp/qogir-icon-theme
    cmd: ./install.sh
  become: true
  register: tty_theme
  when: qogir_icon_check.stat.exists == 0

# Tmux theme

