# here are all the customization for catppuccin themes
# we checkout the different themes from github organizations:

- name: Clone a github repository
  git:
    repo: https://github.com/sqlite/sqlite.git
    dest: /home/benjilegnard/repos/
    clone: yes
    update: yes
