---
# here are all the customization for catppuccin themes
# we checkout the different themes from github organizations:

# things used by the themes
- name: Install fonts and themes deps
  become: true
  ansible.builtin.apt:
    name:
      - fonts-font-awesome
      - fonts-hack
      - fonts-noto-color-emoji
    install_recommends: false
    state: present

#
# GRUB
#
- name: Clone catppuccin/grub
  ansible.builtin.git:
    repo: https://github.com/catppuccin/grub.git
    version: 803c5df
    dest: ./theme/catppuccin/grub
    accept_hostkey: true
    clone: true
    update: true
    depth: 1

- name: Copy theme files for grub
  become: true
  ansible.builtin.copy:
    src: ./theme/catppuccin/grub/src/catppuccin-mocha-grub-theme
    dest: /usr/share/grub/themes
    owner: root
    group: root
    mode: "755"

- name: Check if theme is configured in the boot command
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: ^GRUB_THEME=".*
    state: absent
  check_mode: true
  register: grub_theme_check
  changed_when: false

- name: Enable the theme in grub default configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha-grub-theme/theme.txt"
    # create: true
  when: grub_theme_check.found == 0

- name: Update grub if theme was added
  become: true
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_theme_check.found == 0
  changed_when: true

# todo; maybe also check and set GRUB_GFXMODE=1920x1080

#
# TTY : https://github.com/catppuccin/tty
#
- name: Clone catppuccin/tty
  ansible.builtin.git:
    repo: https://github.com/catppuccin/tty.git
    version: d18074f
    dest: ./theme/catppuccin/tty
    clone: true
    update: true
    depth: 1

- name: Check if tty theme is configured in the boot command
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=".*vt.*"$
    state: absent
  check_mode: true
  register: grub_tty_check
  changed_when: false

- name: Generate mocha theme
  ansible.builtin.command:
    chdir: ./theme/catppuccin/tty
    cmd: ./generate.sh mocha
  register: tty_theme
  when: grub_tty_check.found == 0

# FIXME; this does not work when config exists
- name: Configure tty theme in CRUB_CMDLINE_LINUX options
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    backrefs: true
    regexp: "^(GRUB_CMDLINE_LINUX=\")(.*\")$"
    line: '\1 {{ tty_theme.stdout }}\2'
  when: grub_tty_check.found == 0

- name: Update grub if tty config was added
  become: true
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_tty_check.found == 0

#
# Waybar https://github.com/catppuccin/waybar
#
- name: Clone catppuccin/waybar
  ansible.builtin.git:
    repo: https://github.com/catppuccin/waybar.git
    version: f74ab1e
    dest: ./theme/catppuccin/waybar
    clone: true
    update: true
    depth: 1

- name: Ensure waybar config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/waybar
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy mocha theme files for waybar
  ansible.builtin.copy:
    src: ./theme/catppuccin/waybar/themes/mocha.css
    dest: /home/{{ user }}/.config/waybar
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

#
# GTK ( TODO ) https://github.com/catppuccin/gtk
#
- name: Clone catppuccin/gtk
  ansible.builtin.git:
    repo: https://github.com/catppuccin/gtk.git
    version: v0.7.1
    dest: ./theme/catppuccin/gtk
    clone: true
    update: true
    depth: 1
