---
- name: Add vscodium repository key
  ansible.builtin.get_url:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    dest: /etc/apt/trusted.gpg.d/vscodium.asc
    mode: "644"
    force: true

- name: Add vscode repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 trusted=yes] https://packages.microsoft.com/repos/vscode stable main"
    filename: "vscode"
    state: present

- name: Install codium
  ansible.builtin.apt:
    name: codium
    state: present

- name: Remove VSCode
  ansible.builtin.apt:
    name: code
    state: absent

- name: List installed extensions with versions
  ansible.builtin.command:
    cmd: codium --no-sandbox --list-extensions --show-versions
  register: installed_extensions

- name: Install VSCodium extensions
  ansible.builtin.command:
    cmd: codium --no-sandbox --install-extension {{ item }}
    when: "'{{ item }}' not in installed_extensions"
    register: installation_result
  loop:
    - Angular.ng-template
    - Antyos.openscad
    - Catppuccin.catppuccin-vsc
    - Catppuccin.catppuccin-vsc-icons
    - DotJoshJohnson.xml
    - EditorConfig.EditorConfig
    - Orta.vscode-jest
    - Prisma.prisma
    - SonarSource.sonarlint-vscode
    - VisualStudioExptTeam.intellicode-api-usage-examples
    - VisualStudioExptTeam.vscodeintellicode
    - ZixuanChen.vitest-explorer
    - alexkrechik.cucumberautocomplete
    - asciidoctor.asciidoctor-vscode
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - dbaeumer.vscode-eslint
    - deque-systems.vscode-axe-linter
    - esbenp.prettier-vscode
    - firefox-devtools.vscode-firefox-debug
    - firsttris.vscode-jest-runner
    - hashicorp.terraform
    - hbenl.vscode-test-explorer
    - hediet.vscode-drawio
    - jebbs.plantuml
    - lucono.karma-test-explorer
    - ms-azuretools.vscode-docker
    - ms-edgedevtools.vscode-edge-devtools
    - ms-playwright.playwright
    - ms-vscode-remote.remote-containers
    - ms-vscode.makefile-tools
    - ms-vscode.test-adapter-converter
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - nrwl.angular-console
    - redhat.ansible
    - rust-lang.rust-analyzer
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-french
    - stylelint.vscode-stylelint
    - sysoev.language-stylus
    - timonwong.shellcheck
    - vscjava.vscode-gradle
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscodevim.vim
    - yzhang.markdown-all-in-one

- name: Uninstall VSCode extensions
  ansible.builtin.command:
    cmd: codium --no-sandbox --uninstall-extension {{ item }}
  loop:
    - ms-edgedevtools.vscode-edge-devtools
