# - name: Add apt repository for vscode
#   apt_repository: https://packages.microsoft.com/repos/code

- name: Install command line tools
  apt: name={{item}}
  with_items:
    - code

- name: Install VSCode extensions
  ansible.builtin.shell:
    cmd: code --no-sandbox --install-extension  {{item}}
  with_items:
    - Angular.ng-template
    - Antyos.openscad
    - Catppuccin.catppuccin-vsc
    - Catppuccin.catppuccin-vsc-icons
    - DotJoshJohnson.xml
    - EditorConfig.EditorConfig
    - Orta.vscode-jest
    - Prisma.prisma
    - SonarSource.sonarlint-vscode
    - VisualStudioExptTeam.intellicode-api-usage-examples
    - VisualStudioExptTeam.vscodeintellicode
    - ZixuanChen.vitest-explorer
    - alexkrechik.cucumberautocomplete
    - asciidoctor.asciidoctor-vscode
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - dbaeumer.vscode-eslint
    - deque-systems.vscode-axe-linter
    - esbenp.prettier-vscode
    - firefox-devtools.vscode-firefox-debug
    - firsttris.vscode-jest-runner
    - hashicorp.terraform
    - hbenl.vscode-test-explorer
    - hediet.vscode-drawio
    - jebbs.plantuml
    - lucono.karma-test-explorer
    - ms-azuretools.vscode-docker
    - ms-edgedevtools.vscode-edge-devtools
    - ms-playwright.playwright
    - ms-vscode-remote.remote-containers
    - ms-vscode.makefile-tools
    - ms-vscode.test-adapter-converter
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - nrwl.angular-console
    - redhat.ansible
    - rust-lang.rust-analyzer
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-french
    - stylelint.vscode-stylelint
    - sysoev.language-stylus
    - timonwong.shellcheck
    - vscjava.vscode-gradle
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscodevim.vim
    - yzhang.markdown-all-in-one

- name: Uninstall VSCode extensions
  ansible.builtin.shell:
    cmd: code --no-sandbox --uninstall-extension {{item}}
  with_items:
    - ms-edgedevtools.vscode-edge-devtools
