---

- name: Add docker key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 trusted=yes] https://download.docker.com/linux/ubuntu focal stable"
    filename: "docker"
    state: present