---
# i3, a tiling manager, setup with rofi, dunst and polybar
- name: Install i3 and related packages
  become: true
  ansible.builtin.apt:
    name:
      - i3
      - polybar
      - rofi
      - xorg
      - feh
      - arandr
      - dunst
      - maim
      - xclip
      - xdotool
    install_recommends: false
    state: present

- name: Ensure config directories exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/{{ item }}/
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - i3
    - i3status
    - rofi
    - dunst
    - polybar
    - X11

- name: Copy configuration files
  ansible.builtin.copy:
    src: ./config/{{ item }}
    dest: /home/{{ user }}/.config/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - i3/config
    - rofi/config.rasi
    - dunst/dunstrc
    - polybar/config.ini
    - polybar/polybar.sh

- name: Copy Xresources config
  ansible.builtin.copy:
    src: /home/{{ user }}/.config/X11/Xresources
    dest: /home/{{ user }}/.Xresources
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy default xinit
  ansible.builtin.copy:
    src: /etc/X11/xinit/xinitrc
    dest: /home/{{ user }}/.xinitrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Add i3 to xinitrc
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.xinitrc
    line: "exec i3"
