---
- name: Add neovim repository
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    codename: mantic
    filename: "neovim"
  become: true

- name: Install neovim
  become: true
  apt:
    name:
      - neovim
    state: present

- name: Copy nvim config directory
  ansible.builtin.copy:
    src: ./config/nvim
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"
