---
- name: Add neovim repository
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    codename: mantic
    filename: "neovim"
  become: true

- name: Install neovim
  become: true
  apt:
    name:
      - neovim
    state: present

- name: Copy nvim config directory
  ansible.builtin.copy:
    src: ./config/nvim
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Uninstall vim
  become: true
  apt:
    name:
      - vim-tiny
      - vim-common
      - vi
    state: absent

- name: Update alternatives for vi
  community.general.alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item}}
    path: /usr/bin/nvim
    priority: 60
    state: selected
  become: true
  loop:
    - editor
    - vi
    - vim
