---
- name: Add neovim repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    filename: neovim

- name: Install neovim
  ansible.builtin.apt:
    name: neovim
    state: present

- name: Copy nvim config directory
  ansible.builtin.copy:
    src: ./config/nvim
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"
