---
- name: Get neovim repository signing key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9DBB0BE9366964F134855E2255F96FCF8231B6DD
    dest: /etc/apt/keyrings/neovim.asc
    mode: '0644'
    force: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Add neovim repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/neovim.asc] https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu lunar main"
    filename: "neovim"
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install neovim and dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      # treesitter dependencies
      - gcc
      - g++
      # main package
      - neovim
    state: present

- name: Copy nvim config directory
  ansible.builtin.copy:
    src: ./config/nvim
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Uninstall vim
  become: true
  apt:
    name:
      - vim-tiny
      - vim-common
      - vi
    state: absent

- name: Update alternatives for vi
  community.general.alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item}}
    path: /usr/bin/nvim
    priority: 60
    state: selected
  become: true
  loop:
    - editor
    - vi
    - vim
