---
- name: Get obs-studio repository signing key on ubuntu
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xBC7345F522079769F5BBE987EFC71127F425E228
    dest: /etc/apt/keyrings/obsproject.asc
    mode: '0644'
    force: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Add obsproject repository on ubuntu
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/obsproject.asc] https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble main"
    filename: "obsproject"
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install obs-studio
  become: true
  ansible.builtin.apt:
    name:
      # some optional obs dependencies
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - pipewire
      - wireplumber
      # required obs dependencies
      - v4l2loopback-dkms
      - ffmpeg
      # main package
      - obs-studio
    state: present
  when: ansible_distribution == 'Ubuntu'

#
# Catppuccin theme for obs https://github.com/catppuccin/obs
#
- name: Check if theme is installed
  ansible.builtin.stat:
    path: /home/{{ user }}/.config/obs-studio/themes
  register: obs_theme_check

- name: Clone catppuccin/obs
  ansible.builtin.git:
    repo: https://github.com/catppuccin/obs.git
    version: e7c4fcf
    dest: ./temp/catppuccin/obs
    clone: true
    update: true
    depth: 1
  when: obs_theme_check.stat.exists == false

- name: Ensure obs config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/obs-studio/themes
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  when: obs_theme_check.stat.exists == false

- name: Copy mocha theme file for obs
  ansible.builtin.copy:
    src: ./temp/catppuccin/obs/themes
    dest: /home/{{ user }}/.config/obs-studio/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  when: obs_theme_check.stat.exists == false
