# Sway, a tiling manager. Here we install all things related to the sway and wayland desktop environment.

# Debian experimental has more recent versions of sway than ubuntu, so we add it
- name: Add apt keys for debian repositories
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ key_item }}"
  with_items:
    - "04EE7237B7D453EC"
    - "648ACFD622F3D138"
  loop_control:
    loop_var: key_item

- name: Add Debian experimental repository for latest Sway and Wlroots versions
  become: yes
  apt_repository:
    repo: deb http://httpredir.debian.org/debian experimental main
    state: present

- name: Install sway and wayland related packages
  become: yes
  apt:
    name:
      - sway
      - grimshot
      - slurp
      - sway-notification-center
      - swayidle
      - swaylock
      - waybar
      - wayland-protocols
      - wdisplays
      - wf-recorder
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - sddm
      - wofi
      - zenity
    install_recommends: false
    # default_release: experimental
    state: present

- name: Ensure config directories exists
  file:
    path: "/home/{{ user }}/.config/{{ item }}/"
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - sway
    - swaylock
    - swaync
    - waybar
    - wofi

- name: Copy configuration file for wofi
  copy:
    src: "./config/wofi/{{ item }}"
    dest: "/home/{{ user }}/.config/wofi/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
    loop:
      - config
      - style.css
      - wofi-emoji
- name: Copy configuration file for sway
  copy:
    src: ./config/sway/config
    dest: "/home/{{ user }}/.config/sway/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration file for swaylock
  copy:
    src: ./config/swaylock/config
    dest: "/home/{{ user }}/.config/swaylock/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration file for sway notification center
  copy:
    src: ./config/swaync/style.css
    dest: "/home/{{ user }}/.config/swaync/"

- name: Copy config files for waybar
  copy:
    src: "./config/waybar/{{ item }}"
    dest: "/home/{{ user }}/.config/waybar/"
  loop:
    - style.css
    - config



# todo: wl-imirror
