---
# Sway, a tiling manager. Here we install all things related to the sway and wayland desktop environment.
- name: Install sway and wayland related packages
  become: true
  ansible.builtin.apt:
    name:
      - at-spi2-core
      - gnome-keyring
      - grim
      - kitty
      - network-manager-applet
      - pipewire
      - seatd
      - slurp
      - sway
      - sway-notification-center
      - swayidle
      - swaylock
      - waybar
      - wayland-protocols
      - wdisplays
      - wf-recorder
      - wireplumber
      - wl-clipboard
      - wtype
      - xdg-desktop-portal-wlr
      - zenity
    install_recommends: false
    state: present

- name: Ensure config directories exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/{{ item }}/
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - sway
    - swaylock
    - swaync
    - waybar
    - rofi
    - kitty

- name: Copy configuration files for rofi
  ansible.builtin.copy:
    src: ./config/rofi/config.rasi
    dest: /home/{{ user }}/.config/rofi/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy theme file for rofi
  ansible.builtin.copy:
    src: ./config/rofi/catppuccin-mocha.rasi
    dest: /home/{{ user }}/.local/share/rofi/themes/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration files for sway
  ansible.builtin.copy:
    src: ./config/sway/{{ item }}
    dest: /home/{{ user }}/.config/sway/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - config
    - import-gsettings
    - init-xdg
    - start-keyring

- name: Copy configuration file for swaylock
  ansible.builtin.copy:
    src: ./config/swaylock/config
    dest: /home/{{ user }}/.config/swaylock/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration file for sway notification center
  ansible.builtin.copy:
    src: ./config/swaync/style.css
    dest: /home/{{ user }}/.config/swaync/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy config files for waybar
  ansible.builtin.copy:
    src: ./config/waybar/{{ item }}
    dest: /home/{{ user }}/.config/waybar/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - style.css
    - config.jsonc

- name: Copy configuration file for kitty
  ansible.builtin.copy:
    src: ./config/kitty/kitty.conf
    dest: /home/{{ user }}/.config/kitty/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Update alternatives, set kitty as default terminal emulator
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/kitty

# Install grimshot from github repo (not in devuan)

- name: Install grimshot from sway-contrib
  ansible.builtin.git:
    repo: https://github.com/OctopusET/sway-contrib.git
    version: "1.9"
    dest: ./themes/sway-contrib
    clone: true
    update: true
    depth: 1

- name: Copy
  ansible.builtin.copy:
    src: ./themes/sway-contrib/grimshot
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "755"

# various configs and env vars
- name: Enable theme in profile and rc files
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/{{ item }}
    line: export XDG_RUNTIME_DIR=/run/user/{{ uid }}
    create: true
  loop:
    - .zshrc
    - .bashrc

- name: Set current desktop in rc files
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/{{ item }}
    line: export XDG_CURRENT_DESKTOP=sway
    create: true
  loop:
    - .zshrc
    - .bashrc

#- name: Autostart sway on tty1 login
#  ansible.builtin.copy:
#    content: |
#      #!/bin/zsh
#      if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]]; then
#        exec sway
#      fi
#    dest: /home/{{ user }}/.zprofile
#    owner: "{{ user }}"
#    group: "{{ user }}"
#    mode: "755"
