---
# Sway, a tiling manager. Here we install all things related to the sway and wayland desktop environment.
- name: Install sway and wayland related packages
  become: true
  ansible.builtin.apt:
    name:
      - sway
      - grimshot
      - slurp
      - sway-notification-center
      - swayidle
      - swaylock
      - waybar
      - wayland-protocols
      - wdisplays
      - wf-recorder
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - wofi
      - foot
      - zenity
      - gnome-keyring
      - pipewire
      - wireplumber
    install_recommends: false
    state: present

- name: Ensure config directories exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/{{ item }}/
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - sway
    - swaylock
    - swaync
    - waybar
    - wofi
    - foot

- name: Copy configuration file for wofi
  ansible.builtin.copy:
    src: ./config/wofi/{{ item }}
    dest: /home/{{ user }}/.config/wofi/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - config
    - style.css
    - wofi-emoji

- name: Copy configuration file for sway
  ansible.builtin.copy:
    src: ./config/sway/config
    dest: /home/{{ user }}/.config/sway/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration file for swaylock
  ansible.builtin.copy:
    src: ./config/swaylock/config
    dest: /home/{{ user }}/.config/swaylock/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy configuration file for sway notification center
  ansible.builtin.copy:
    src: ./config/swaync/style.css
    dest: /home/{{ user }}/.config/swaync/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Copy config files for waybar
  ansible.builtin.copy:
    src: ./config/waybar/{{ item }}
    dest: /home/{{ user }}/.config/waybar/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - style.css
    - config

- name: Copy configuration file for foot
  ansible.builtin.copy:
    src: ./config/foot/foot.ini
    dest: /home/{{ user }}/.config/foot/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

# todo: wl-imirror
