# Sway, a tiling manager. Here we install all things related to the sway and wayland desktop environment.

# Debian experimental has more recent versions of sway than ubuntu, so we add it
- name: Add apt keys for debian repositories
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ key_item }}"
  with_items:
    - "04EE7237B7D453EC"
    - "648ACFD622F3D138"
  loop_control:
    loop_var: key_item

# add the repository to the host.
- name: Add Debian experimental repository for latest Sway and Wlroots versions
  become: yes
  apt_repository:
    repo: deb http://httpredir.debian.org/debian experimental main
    state: present

#
- name: Install sway and wayland related packages
  become: yes
  apt:
    name:
      - grimshot
      - slurp
      - sway
      - sway-notification-center
      - swayidle
      - swaylock
      - waybar
      - qt6-wayland
      - wdisplays
      - wf-recorder
      - wl-clipboard
      # - wl-mirror
      - xdg-desktop-portal-wlr
      - sddm
      - fuzzel
      - zenity
    install_recommends: false
    state: present

- name: Ensure config directories exists
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    recurse: true
    state: directory
  loop:
    - fuzzel
    - sway
    - swaylock
    - swaync
    - waybar

- name: Copy configuration file for fuzzel
  copy:
    src: ./config/fuzzel/fuzzel.ini
    dest: "{{ ansible_env.HOME }}/.config/fuzzel"

- name: Copy configuration file for sway
  copy:
    src: ./config/sway/config
    dest: "{{ ansible_env.HOME }}/.config/sway"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Copy configuration file for swaylock
  copy:
    src: ./config/swaylock/config
    dest: "{{ ansible_env.HOME }}/.config/swaylock"

- name: Copy configuration file for sway notification center
  copy:
    src: ./config/swaync/style.css
    dest: "{{ ansible_env.HOME }}/.config/swaync"

- name: Copy config files for waybar
  copy:
    src: "./config/waybar/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/waybar"
  loop:
    - style.css
    - config



# todo: wl-imirror
