---
- name: Install CLI packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - tmux
    - jq
    - git
    - tig
    - vim
    - zsh
    - curl
    - zip

# todo: configure zsh and powerline
