---
- name: Install CLI packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - tmux
    - jq
    - git
    - tig
    - zsh
    - curl
    - zip
    - fzf

- name: Configure zsh
  ansible.builtin.shell: |
    chsh -s $(which zsh) {{ user }}

# starship

- name: Checks if starship is available
  ansible.builtin.command: command -v starship >/dev/null 2>&1
  register: starship_available
  ignore_errors: true

- name: Download starship installation script
  when: "starship_available.rc != 0"
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-installer.sh
    mode: 'u+rwx'
  register: starship_download

- name: Run the install starship script
  ansible.builtin.shell: /tmp/starship-installer.sh -y
  when: starship_download.changed

- name: Remove the starship-installer.sh
  ansible.builtin.file:
    path: /tmp/starship-installer.sh
    state: absent

- name: Add starship init to bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    line: 'eval "$(starship init bash)"'
    state: present
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Add starship init to zshrc
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: 'eval "$(starship init zsh)"'
    state: present
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Copy starship configuration
  ansible.builtin.copy:
    src: ./config/starship.toml
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

# Install Hack font

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.local/share/fonts
    state: directory

- name: Hack exists
  ansible.builtin.shell: "ls /home/{{ user }}/.local/share/fonts/Hack*Nerd*Font*"
  register: hack_exists
  ignore_errors: true
  no_log: true

- name: Download and extract Hack font
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
    dest: /home/{{ user }}/.local/share/fonts
    remote_src: true

# tmux

- name: Ensure tmux config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/{{ item }}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - .config/tmux
    - .tmux/plugins/tpm

- name: Copy tmux configuration
  ansible.builtin.copy:
    src: ./config/tmux/tmux.conf
    dest: /home/{{ user }}/.config/tmux/tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Clone and install tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /home/{{ user }}/.tmux/plugins/tpm
    version: 99469c4
