---
- name: Install CLI packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - tmux
    - jq
    - git
    - tig
    - zsh
    - curl
    - zip
    - fzf

- name: Configure zsh
  ansible.builtin.shell: |
    chsh -s $(which zsh) {{ user }}

# starship

- name: Checks if starship is available
  ansible.builtin.command: command -v starship >/dev/null 2>&1
  register: starship_available
  no_log: true
  ignore_errors: true

- name: Download starship installation script
  when: "starship_available.rc != 0"
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-installer.sh
    mode: 'u+rwx'
  register: starship_download

- name: Run the install starship script
  ansible.builtin.shell: /tmp/starship-installer.sh -y
  when: starship_download.changed

- name: Remove the starship-installer.sh
  ansible.builtin.file:
    path: /tmp/starship-installer.sh
    state: absent

- name: Add starship init to bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    line: 'eval "$(starship init bash)"'
    state: present
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Add starship init to zshrc
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: 'eval "$(starship init zsh)"'
    state: present
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Copy starship configuration
  ansible.builtin.copy:
    src: ./config/starship.toml
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Checks if oh-my-zsh is available
  ansible.builtin.command: command -v omz >/dev/null 2>&1
  register: omz_available
  no_log: true
  ignore_errors: true

- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh-installer.sh
    mode: 'u+rwx'
  register: omz_download
  when: "omz_available.rc != 0"

- name: Run the install oh-my-zsh script
  ansible.builtin.shell: /tmp/ohmyzsh-installer.sh
  when: omz_download.changed
