---
# setup vim config
- name: Install vim packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim

- name: Ensure vim config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.vim/{{ item }}
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    - autoload
    - plugged
    - bundle

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/plug.vim
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Install vim config
  ansible.builtin.copy:
    src: ./config/vim/.vimrc
    dest: /home/{{ user }}/.vimrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Clone catppuccin/vim
  ansible.builtin.git:
    repo: https://github.com/catppuccin/vim.git
    version: "be4725c"
    dest: ./theme/catppuccin/vim
    clone: true
    update: true
    depth: 1
    recursive: true

- name: Copy catppuccin vim colors
  ansible.builtin.copy:
    src: ./theme/catppuccin/vim/colors
    dest: /home/{{ user }}/.vim/colors
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
