---
# download wallpapers
# to get all linked images from a web page, use this javascript snippet in the browser console:
# let links = [];document.querySelectorAll('a').forEach((node)=>{links.push(node.href)});
# let images = [...new Set(links)].filter(href => /.*\.jpg$/g.test(href)).map(img => img.split('/').pop().replace('.jpg',''))
# console.log(images);
- name: Checks if wallpaper directory exists
  ansible.builtin.stat:
    path: /home/{{ user }}/Images/SimonStalenhag/
  register: wallpaper_directory

- name: Debug wallpaper directory
  ansible.builtin.debug:
    var: wallpaper_directory.stat.exists

- name: Ensure wallpaper directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/Images/SimonStalenhag/
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"

- name: Download "tales from the loop" wallpapers
  when: wallpaper_directory.stat.exists == 0
  ansible.builtin.get_url:
    url: "https://www.simonstalenhag.se/tftlbig/{{ item }}.jpg"
    dest: /home/{{ user }}/Images/SimonStalenhag/tftl_{{ item }}.jpg
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop: "{{ range(1, 47) | difference([21]) | list }}"

- name: Download "things from the flood" wallpapers
  when: wallpaper_directory.stat.exists == 0
  ansible.builtin.get_url:
    url: "https://www.simonstalenhag.se/tftfbig/{{ item }}.jpg"
    dest: /home/{{ user }}/Images/SimonStalenhag/tftf_{{ item }}.jpg
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop: "{{ range(4, 56) | list }}"

- name: Download more wallpapers
  when: wallpaper_directory.stat.exists == 0
  ansible.builtin.get_url:
    url: "https://www.simonstalenhag.se/bilderbig/{{ item }}.jpg"
    dest: /home/{{ user }}/Images/SimonStalenhag/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
  loop:
    # the labyrinth :
    - l_ash02_big
    - l_fb_01_big
    - l_fb_04_big
    - l_fb_06_big
    - l_fb_07_big
    - l_fb_08_big
    - l_fb_11_big
    - l_ash03_big
    - l_ash04_big
    - l_ash05_big
    - l_ash06_big
    - l_garage01_big
    - l_int01_big
    - l_int02_big
    - l_int03_big
    - l_ash07_big
    - l_ash08_big
    - l_ash09_big
    - l_ash10_big
    - l_ash11_big
    - l_int05_big
    - l_ash12_big
    - l_ash13_big
    - l_int06_big
    - l_ash14_big
    - l_ash15_big
    - l_ash16_big
    - l_int07_5_big
    - l_ash17_big
    - l_fb_09_big
    - l_fb_10_big
    - l_fb_12_big
    # the electric state :
    - by_dust01_2560
    - by_dust02_2560
    - by_border_2880
    - by_ducks_2560
    - by_warmachines5_1920
    - by_warmachines7_1920
    - by_upload1_2560
    - by_burned_2560
    - by_billboards2_2560
    - by_on_ramp_2560
    - by_billboards_2560
    - by_waiters_2560
    - by_mound_1920
    - by_mules_1920
    - by_warmachines1_2560
    - by_warmachines3_1920
    - by_mainservers1_1920
    - by_mainservers2_2560
    - by_cablers_1920
    - by_wipers_1920
    - by_renderfarm_1920
    - by_upload2_2560
    - by_themascot_1920
    - by_memorial_1920
    - by_nestingcliffs_2560
    - by_belltowers_2880
    - by_hello_1920
    - by_gathering3_2880
    - by_procession_1920
    - by_gathering2_2560
    - by_sculptures_1920
    - by_housevisit_2560
    - by_conception_1920
    - by_localservers_2560
    - by_localservers2_2560
    - by_roadwork_1920
    - by_warmachines4_1920
    - by_warmachines8_1920
    - by_warmachines2_2560
    - by_crossing_2560
    - by_home_arrival_2560
    - by_home_2560
    - by_home2_2560
    - by_home3_2560
    - by_home4_2560
    - by_home5_1920
    - by_home6_2560
    - by_scavengers_1920
