---
# install rust
- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Install rustup
  when: cargo_exists is failed
  ansible.builtin.apt:
    name: rustup
    state: present

- name: Install rust
  when: cargo_exists is failed
  shell: rustup default stable

- name: Install yazi crate
  ansible.builtin.command:
    cmd: cargo install --locked yazi-fm yazi-cli

- name: Install optional dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - file
    - 7zip
    - fzf
    - zoxide
    - wl-clipboard
    - imagemagick
    - ffmpegthumbnailer

- name: Add yazi function to .zshrc
  ansible.builtin.blockinfile:
    marker: ""
    path: /home/{{ user }}/.zshrc
    block: |
      # utility function for yazi
      function yy() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$@" --cwd-file="$tmp"
        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
                builtin cd -- "$cwd"
        fi
        rm -f -- "$tmp"
      }
    state: present
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

